name: powerplatrelease

on:
  workflow_dispatch
        
jobs:
  build:

    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: 'https://org08653f58.crm.dynamics.com'
        user-name: 'fdiaz@thorsolutions365.onmicrosoft.com'
        password-secret: ${{ secrets.PPPASSWORD }}
        solution-name: 'teamstrial'
        solution-output-file: 'aSolution1.zip'
        working-directory: 'out'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/aSolution1.zip'
        solution-folder: 'out/solutions/solution one'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: 'https://org7765a1e0.crm.dynamics.com'
        user-name: 'fdiaz@thorsolutions365.onmicrosoft.com'
        password-secret: ${{ secrets.PPPASSWORD }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'out/solutions/solution one'
        solution-target-folder: 'src/solutions/solution1'
        token: ${{ secrets.GITHUB_TOKEN }}
