
name: Acción para pruebas .net

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Descargar código 
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Dependencias
      run: dotnet restore ./anamportalboletas/anamportalboletas.sln

    - name: Build
      run: dotnet build ./anamportalboletas/anamportalboletas.sln --configuration Release

    - name: Test
      run: dotnet test ./anamportalboletas/anamportalboletas.sln --logger "trx;LogFileName=test-results.trx" || true

    #- name: Test Report
    #  uses: dorny/test-reporter@v1
    #  if: always()
    #  with:
    #    name: DotNET Tests
    #    path: "**/test-results.trx"                            
    #    reporter: dotnet-trx
    #    fail-on-error: true

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test-results/**/*.xml
          test-results/**/*.trx
          test-results/**/*.json